export const MONEY_AFFIRMATIONS = [
	'Money, incoming!',
	'Cash explosion!',
	'Wealth unlocked!',
	'Dollars raining down!',
	'Your fortune awaits!',
	'Cha-ching!',
	'Get that money!',
	'Rich vibes only!',
	'Wallet overflowing!',
	'Financial jackpot!',
	'Money magnet activated!',
	'Abundance unlocked!',
	'Prosperity party!',
	'Bank account boost!',
	"You're rolling in it!",
	'Profit power!',
	'Money magic!',
	'Instant wealth!',
	'Gold rush!',
	"Your money's here!",
	'Financial win!',
	'Money multiplied!',
	'Wealth wave!',
	'Cash flow!',
	"You're a money pro!",
	'Fortune favors you!',
	"Money's on its way!",
	"You're a money boss!",
	'Financial freedom now!',
	'Money on demand!',
	'Get paid!',
	'Your wealth is expanding!',
	"Money's your best friend!",
	'You are a money miracle!',
	"You're a money superstar!",
	'Money is your playground!',
	"You're a money rockstar!",
	'Money is your superpower!',
	'You are a money champion!',
	'Money is your destiny!',
	"You're a money legend!",
	'Money is your reward!',
	"You're a money innovator!",
	'Money is your partner!',
	"You're a money visionary!",
	'Money is your adventure!',
	"You're a money alchemist!",
	'Money is your journey!',
	"You're a money architect!",
	'Money is your companion!',
	"You're a money pioneer!",
	'Money is your ally!',
	"You're a money strategist!",
	'Money is your tool!',
	"You're a money catalyst!",
	'Money is your energy!',
	"You're a money influencer!",
	'Money is your expression!',
	"You're a money champion!",
	'Money is your creation!',
	"You're a money mentor!",
	'Money is your experience!',
	"You're a money advocate!",
	'Money is your freedom!',
	"You're a money ambassador!",
	'Money is your growth!',
	"You're a money leader!",
	'Money is your fulfillment!',
	"You're a money trailblazer!",
	'Money is your creation!',
	'Money is yours!',
	'You are money!',
	'Money loves you!',
	'You are wealthy!',
	'Money is abundant!',
	'You are prosperous!',
	'Money is easy!',
	'You are deserving!',
	'Money is fun!',
	'You are lucky!',
	'Money is flowing!',
	'You are magnetic!',
	'Money is here!',
	'You are rich!',
	'Money is now!',
	'You are abundant!',
	'Money is yours!',
	'You are successful!',
	'Money is good!',
	'You are powerful!',
];
